services:
  - type: web
    name: eventportal
    env: python
    buildCommand: pip install -r eventportal/requirements.txt && python eventportal/manage.py collectstatic --noinput
    startCommand: gunicorn eventportal.wsgi:application  # This line is correct
    # You may also need to adjust the command to run the server if you want to use it directly
    # For example, if you want to run the development server (not recommended for production):
    # startCommand: python eventportal/manage.py runserver 0.0.0.0:8000
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: eventportal-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS 
        value: "https://*.onrender.com"

databases:
  - name: eventportal-db
    databaseName: eventportal
    plan: free
    ipAllowList: [] # Only allow internal connections
