services:
  - type: web
    name: eventportal
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn eventportal.wsgi:application
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: eventportal-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS 
        value: "https://*.onrender.com"

databases:
  - name: eventportal-db
    databaseName: eventportal
    plan: free
    ipAllowList: [] # Only allow internal connectionsservices:
  - type: web
    name: eventportal
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn eventportal.wsgi:application
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: eventportal-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.10.12
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS 
        value: "https://*.onrender.com"

databases:
  - name: eventportal-db
    databaseName: eventportal
    plan: free
    ipAllowList: [] # Only allow internal connections